---
- hosts: all
  become: yes
  become_method: sudo
  tasks: 
  - name: "Update"
    apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
    force_apt_get: true
  - name: "install curl"
    apt:
    name: curl
    state: latest
